### ISSUE TITLE
Make Error Windows 10

### ISSUE THREAD

**Issue by Kimrli** [janhubicka/Color-Screen#2] opened 2024-07-03 10:39 UTC
With commit 68708b94edee32f01ce4818ee3ed6ae03d7ca172, cmd `make` fails with following error:
```
In file included from L:/Aplikace/msys64/mingw64/include/c++/13.2.0/cwchar:44,
                 from L:/Aplikace/msys64/mingw64/include/c++/13.2.0/bits/postypes.h:40,
                 from L:/Aplikace/msys64/mingw64/include/c++/13.2.0/iosfwd:42,
                 from L:/Aplikace/msys64/mingw64/include/c++/13.2.0/bits/shared_ptr.h:52,
                 from L:/Aplikace/msys64/mingw64/include/c++/13.2.0/memory:80,
                 from finetune.C:1:
finetune.C: In function 'finetune_result finetune(render_parameters&, const scr_to_img_parameters&,
const image_data&, int, int, const finetune_parameters&, progress_info*)':
finetune.C:1420:185: error: expected unqualified-id before '(' token
 1420 | #pragma omp parallel for default(none) collapse (2) schedule(dynamic) shared(fparams,maxtile
s,rparam,best_uncertainity,verbose,std::nothrow,imgp,twidth,theight,txmin,tymin,bw,progress,stderr,m
app,render,best_solver) if (maxtiles > 1 && !(fparams.flags & finetune_no_progress_report))
      |
                                                                                            ^~~~~~
make[3]: *** [Makefile:937: libcolorscreen_la-finetune.lo] Error 1
make[3]: Leaving directory '/l/Documents/Color-Screen/Color-Screen/src/libcolorscreen'
make[2]: *** [Makefile:463: all] Error 2
make[2]: Leaving directory '/l/Documents/Color-Screen/Color-Screen/src/libcolorscreen'
make[1]: *** [Makefile:363: all-recursive] Error 1
make[1]: Leaving directory '/l/Documents/Color-Screen/Color-Screen/src'
make: *** [Makefile:392: all-recursive] Error 1
```

**Comment by janhubicka** [comment] 2024-07-03 19:03
I believe this should be fixed in current master

**Comment by Kimrli** [comment] 2024-07-04 11:19
In commit 9539ce8ec5d150c2a5674b01f5ccb0090e3373f6 it moved to another function:
```
In file included from L:/Aplikace/msys64/mingw64/include/c++/13.2.0/cwchar:44,
                 from L:/Aplikace/msys64/mingw64/include/c++/13.2.0/bits/postypes.h:40,
                 from L:/Aplikace/msys64/mingw64/include/c++/13.2.0/bits/char_traits.h:42,
                 from L:/Aplikace/msys64/mingw64/include/c++/13.2.0/string:42,
                 from colorscreen.C:2:
colorscreen.C: In function 'void finetune(int, char**)':
colorscreen.C:1139:134: error: expected unqualified-id before '(' token
 1139 | #pragma omp parallel for default (none) collapse(2) schedule (dynamic) shared (xsteps,ysteps
,rparam,scan,flags,border,progress,param,stderr,orig_tiff_base,simulated_tiff_base,diff_tiff_base,re
sults,multitile)
      |
                                         ^~~~~~
make[2]: *** [Makefile:413: colorscreen.o] Error 1
make[2]: Leaving directory '/l/Documents/Color-Screen/Color-Screen/src/colorscreen'
make[1]: *** [Makefile:363: all-recursive] Error 1
make[1]: Leaving directory '/l/Documents/Color-Screen/Color-Screen/src'
make: *** [Makefile:392: all-recursive] Error 1
```

**Comment by janhubicka** [comment] 2024-07-04 11:31
Shoule be fixed by commit 82008ca7308aeac24198f961947e8ad87cded2f1

**Comment by Kimrli** [comment] 2024-07-04 12:25
I get link error:
```
[INFO] --- native:1.0-alpha-11:link (javah) @ color-screen-gui ---
[DEBUG] Loading mojo org.codehaus.mojo:native-maven-plugin:1.0-alpha-11:link from plugin realm ClassRealm[extension>org.codehaus.mojo:native-maven-plugin:1.0-alpha-11, parent: jdk.internal.loader.ClassLoaders$AppClassLoader@3fee733d]
[DEBUG] Configuring mojo execution 'org.codehaus.mojo:native-maven-plugin:1.0-alpha-11:link:javah' with basic configurator -->
[DEBUG]   (f) attach = true
[DEBUG]   (f) checkStaleLinkage = false
[DEBUG]   (f) compilerProvider = generic-classic
[DEBUG]   (f) dependencyIncludeDirectory = L:\Documents\Color-Screen\Color-Screen-GUI\target\native\include
[DEBUG]   (f) externalLibDirectory = L:\Documents\Color-Screen\Color-Screen-GUI\target\lib
[DEBUG]   (f) linkerEndOptions = [-L/Aplikace/msys64/home/linda/barveni-bin/lib, , -lcolorscreen -lturbojpeg -ltiff -lgsl, -Wl,-add-stdcall-alias, -oL:\Documents\Color-Screen\Color-Screen-GUI\target/render.dll]
[DEBUG]   (f) linkerExecutable = g++
[DEBUG]   (f) linkerFinalName = color-screen-gui
[DEBUG]   (f) linkerFinalNameExt = jar
[DEBUG]   (f) linkerOutputDirectory = L:\Documents\Color-Screen\Color-Screen-GUI\target
[DEBUG]   (f) linkerStartOptions = [-m64 --verbose -shared -fopenmp]
[DEBUG]   (f) project = MavenProject: cz.cuni.mff.colorscreen:color-screen-gui:1.0-SNAPSHOT @ L:\Documents\Color-Screen\Color-Screen-GUI\pom.xml
[DEBUG]   (f) usingLinkerResponseFile = false
[DEBUG]   (f) workingDirectory = L:\Documents\Color-Screen\Color-Screen-GUI
[DEBUG] -- end configuration --
[INFO] cmd.exe /X /C "g++ -m64 --verbose -shared -fopenmp -oL:\Documents\Color-Screen\Color-Screen-GUI\target\color-screen-gui.jar target\objs\cz_cuni_mff_java_digitalColoring_interfaceWithC_ImageData.obj target\objs\cz_cuni_mff_java_digitalColoring_interfaceWithC_ProgressInfo.obj target\objs\cz_cuni_mff_java_digitalColoring_interfaceWithC_Render.obj -L/Aplikace/msys64/home/linda/barveni-bin/lib -lcolorscreen -lturbojpeg -ltiff -lgsl -Wl,-add-stdcall-alias -oL:\Documents\Color-Screen\Color-Screen-GUI\target/render.dll"
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=L:/Aplikace/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/lto-wrapper.exe
Target: x86_64-w64-mingw32
Configured with: ../gcc-13.2.0/configure --prefix=/mingw64 --with-local-prefix=/mingw64/local --build=x86_64-w64-mingw32 --host=x86_64-w64-mingw32 --target=x86_64-w64-mingw32 --with-native-system-header-dir=/mingw64/include --libexecdir=/mingw64/lib --enable-bootstrap --enable-checking=release --with-arch=nocona --with-tune=generic --enable-languages=c,lto,c++,fortran,ada,objc,obj-c++,jit --enable-shared --enable-static --enable-libatomic --enable-threads=posix --enable-graphite --enable-fully-dynamic-string --enable-libstdcxx-filesystem-ts --enable-libstdcxx-time --disable-libstdcxx-pch --enable-lto --enable-libgomp --disable-libssp --disable-multilib --disable-rpath --disable-win32-registry --disable-nls --disable-werror --disable-symvers --with-libiconv --with-system-zlib --with-gmp=/mingw64 --with-mpfr=/mingw64 --with-mpc=/mingw64 --with-isl=/mingw64 --with-pkgversion='Rev3, Built by MSYS2 project' --with-bugurl=https://github.com/msys2/MINGW-packages/issues --with-gnu-as --with-gnu-ld --disable-libstdcxx-debug --with-boot-ldflags=-static-libstdc++ --with-stage1-ldflags=-static-libstdc++
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 13.2.0 (Rev3, Built by MSYS2 project) 
COMPILER_PATH=L:/Aplikace/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/;L:/Aplikace/msys64/mingw64/bin/../lib/gcc/;L:/Aplikace/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/
LIBRARY_PATH=L:/Aplikace/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/;L:/Aplikace/msys64/mingw64/bin/../lib/gcc/;L:/Aplikace/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/lib/../lib/;L:/Aplikace/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../lib/;L:/Aplikace/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/lib/;L:/Aplikace/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../
Reading specs from L:/Aplikace/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../lib/libgomp.spec
COLLECT_GCC_OPTIONS='-m64' '-v' '-shared' '-fopenmp' '-o' 'L:\Documents\Color-Screen\Color-Screen-GUI\target\color-screen-gui.jar' '-L/Aplikace/msys64/home/linda/barveni-bin/lib' '-o' 'L:\Documents\Color-Screen\Color-Screen-GUI\target/render.dll' '-shared-libgcc' '-mtune=generic' '-march=nocona' '-mthreads' '-pthread' '-dumpdir' 'L:\Documents\Color-Screen\Color-Screen-GUI\target/render.dll.'
 L:/Aplikace/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/collect2.exe -plugin L:/Aplikace/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/liblto_plugin.dll -plugin-opt=L:/Aplikace/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/lto-wrapper.exe -plugin-opt=-fresolution=C:\Users\linda\AppData\Local\Temp\cc5kpwSe.res -plugin-opt=-pass-through=-lmingwthrd -plugin-opt=-pass-through=-lmingw32 -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lmoldname -plugin-opt=-pass-through=-lmingwex -plugin-opt=-pass-through=-lmsvcrt -plugin-opt=-pass-through=-lkernel32 -plugin-opt=-pass-through=-lpthread -plugin-opt=-pass-through=-ladvapi32 -plugin-opt=-pass-through=-lshell32 -plugin-opt=-pass-through=-luser32 -plugin-opt=-pass-through=-lkernel32 -plugin-opt=-pass-through=-lmingwthrd -plugin-opt=-pass-through=-lmingw32 -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lmoldname -plugin-opt=-pass-through=-lmingwex -plugin-opt=-pass-through=-lmsvcrt -plugin-opt=-pass-through=-lkernel32 -m i386pep --shared -Bdynamic -e DllMainCRTStartup --enable-auto-image-base -o L:\Documents\Color-Screen\Color-Screen-GUI\target\color-screen-gui.jar -o L:\Documents\Color-Screen\Color-Screen-GUI\target/render.dll L:/Aplikace/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../lib/dllcrt2.o L:/Aplikace/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/crtbegin.o -L/Aplikace/msys64/home/linda/barveni-bin/lib -LL:/Aplikace/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0 -LL:/Aplikace/msys64/mingw64/bin/../lib/gcc -LL:/Aplikace/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/lib/../lib -LL:/Aplikace/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../lib -LL:/Aplikace/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/lib -LL:/Aplikace/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../.. target\objs\cz_cuni_mff_java_digitalColoring_interfaceWithC_ImageData.obj target\objs\cz_cuni_mff_java_digitalColoring_interfaceWithC_ProgressInfo.obj target\objs\cz_cuni_mff_java_digitalColoring_interfaceWithC_Render.obj -lcolorscreen -lturbojpeg -ltiff -lgsl -add-stdcall-alias -lstdc++ -lgomp -lmingwthrd -lmingw32 -lgcc_s -lgcc -lmoldname -lmingwex -lmsvcrt -lkernel32 -lpthread -ladvapi32 -lshell32 -luser32 -lkernel32 -lmingwthrd -lmingw32 -lgcc_s -lgcc -lmoldname -lmingwex -lmsvcrt -lkernel32 L:/Aplikace/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/crtend.o
L:/Aplikace/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: target\objs\cz_cuni_mff_java_digitalColoring_interfaceWithC_ImageData.obj:cz_cuni_mff_java_digitalColoring_interfaceWithC_ImageData.cpp:(.rdata$_ZTV19analyze_base_workerI14dufay_geometryE[_ZTV19analyze_base_workerI14dufay_geometryE]+0x10): undefined reference to `analyze_base::find_best_match(int, int, analyze_base&, int, double*, double*, int, scr_to_img&, scr_to_img&, _iobuf*, progress_info*)'
L:/Aplikace/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: target\objs\cz_cuni_mff_java_digitalColoring_interfaceWithC_ImageData.obj:cz_cuni_mff_java_digitalColoring_interfaceWithC_ImageData.cpp:(.rdata$_ZTV19analyze_base_workerI14dufay_geometryE[_ZTV19analyze_base_workerI14dufay_geometryE]+0x18): undefined reference to `analyze_base::write_screen(char const*, bitmap_2d*, char const**, progress_info*, double, double, double, double, double, double)'
L:/Aplikace/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: target\objs\cz_cuni_mff_java_digitalColoring_interfaceWithC_ImageData.obj:cz_cuni_mff_java_digitalColoring_interfaceWithC_ImageData.cpp:(.rdata$_ZTV19analyze_base_workerI14paget_geometryE[_ZTV19analyze_base_workerI14paget_geometryE]+0x10): undefined reference to `analyze_base::find_best_match(int, int, analyze_base&, int, double*, double*, int, scr_to_img&, scr_to_img&, _iobuf*, progress_info*)'
L:/Aplikace/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: target\objs\cz_cuni_mff_java_digitalColoring_interfaceWithC_ImageData.obj:cz_cuni_mff_java_digitalColoring_interfaceWithC_ImageData.cpp:(.rdata$_ZTV19analyze_base_workerI14paget_geometryE[_ZTV19analyze_base_workerI14paget_geometryE]+0x18): undefined reference to `analyze_base::write_screen(char const*, bitmap_2d*, char const**, progress_info*, double, double, double, double, double, double)'
L:/Aplikace/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: target\objs\cz_cuni_mff_java_digitalColoring_interfaceWithC_ImageData.obj:cz_cuni_mff_java_digitalColoring_interfaceWithC_ImageData.cpp:(.rdata$.refptr._ZTV12analyze_base[.refptr._ZTV12analyze_base]+0x0): undefined reference to `vtable for analyze_base'
collect2.exe: error: ld returned 1 exit status
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  6.138 s
[INFO] Finished at: 2024-07-04T14:20:09+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:native-maven-plugin:1.0-alpha-11:link (javah) on project color-screen-gui: Error executing command line. Exit code:1 -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.mojo:native-maven-plugin:1.0-alpha-11:link (javah) on project color-screen-gui: Error executing command line. Exit code:1
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:333)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:316)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:212)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:174)
    at org.apache.maven.lifecycle.internal.MojoExecutor.access$000 (MojoExecutor.java:75)
    at org.apache.maven.lifecycle.internal.MojoExecutor$1.run (MojoExecutor.java:162)
    at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute (DefaultMojosExecutionStrategy.java:39)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:159)
    at org.apache.maven.lifecycle.internal.MojoExecutor.executeForkedExecutions (MojoExecutor.java:448)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:311)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:212)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:174)
    at org.apache.maven.lifecycle.internal.MojoExecutor.access$000 (MojoExecutor.java:75)
    at org.apache.maven.lifecycle.internal.MojoExecutor$1.run (MojoExecutor.java:162)
    at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute (DefaultMojosExecutionStrategy.java:39)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:159)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:105)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:73)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:53)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:118)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:261)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:173)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:101)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:906)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:283)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:206)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke (DirectMethodHandleAccessor.java:103)
    at java.lang.reflect.Method.invoke (Method.java:580)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:283)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:226)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:407)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:348)
    at org.codehaus.classworlds.Launcher.main (Launcher.java:47)
Caused by: org.apache.maven.plugin.MojoExecutionException: Error executing command line. Exit code:1
    at org.codehaus.mojo.natives.plugin.NativeLinkMojo.execute (NativeLinkMojo.java:231)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:126)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:328)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:316)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:212)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:174)
    at org.apache.maven.lifecycle.internal.MojoExecutor.access$000 (MojoExecutor.java:75)
    at org.apache.maven.lifecycle.internal.MojoExecutor$1.run (MojoExecutor.java:162)
    at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute (DefaultMojosExecutionStrategy.java:39)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:159)
    at org.apache.maven.lifecycle.internal.MojoExecutor.executeForkedExecutions (MojoExecutor.java:448)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:311)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:212)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:174)
    at org.apache.maven.lifecycle.internal.MojoExecutor.access$000 (MojoExecutor.java:75)
    at org.apache.maven.lifecycle.internal.MojoExecutor$1.run (MojoExecutor.java:162)
    at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute (DefaultMojosExecutionStrategy.java:39)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:159)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:105)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:73)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:53)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:118)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:261)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:173)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:101)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:906)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:283)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:206)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke (DirectMethodHandleAccessor.java:103)
    at java.lang.reflect.Method.invoke (Method.java:580)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:283)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:226)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:407)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:348)
    at org.codehaus.classworlds.Launcher.main (Launcher.java:47)
Caused by: org.codehaus.mojo.natives.NativeBuildException: Error executing command line. Exit code:1
    at org.codehaus.mojo.natives.util.CommandLineUtil.execute (CommandLineUtil.java:34)
    at org.codehaus.mojo.natives.linker.AbstractLinker.link (AbstractLinker.java:52)
    at org.codehaus.mojo.natives.plugin.NativeLinkMojo.execute (NativeLinkMojo.java:217)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:126)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:328)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:316)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:212)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:174)
    at org.apache.maven.lifecycle.internal.MojoExecutor.access$000 (MojoExecutor.java:75)
    at org.apache.maven.lifecycle.internal.MojoExecutor$1.run (MojoExecutor.java:162)
    at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute (DefaultMojosExecutionStrategy.java:39)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:159)
    at org.apache.maven.lifecycle.internal.MojoExecutor.executeForkedExecutions (MojoExecutor.java:448)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:311)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:212)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:174)
    at org.apache.maven.lifecycle.internal.MojoExecutor.access$000 (MojoExecutor.java:75)
    at org.apache.maven.lifecycle.internal.MojoExecutor$1.run (MojoExecutor.java:162)
    at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute (DefaultMojosExecutionStrategy.java:39)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:159)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:105)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:73)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:53)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:118)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:261)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:173)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:101)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:906)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:283)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:206)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke (DirectMethodHandleAccessor.java:103)
    at java.lang.reflect.Method.invoke (Method.java:580)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:283)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:226)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:407)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:348)
    at org.codehaus.classworlds.Launcher.main (Launcher.java:47)
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[DEBUG] Shutting down adapter factory; available factories [file-lock, rwlock-local, semaphore-local, noop]; available name mappers [discriminating, file-gav, file-hgav, file-static, gav, static]
[DEBUG] Shutting down 'file-lock' factory
[DEBUG] Shutting down 'rwlock-local' factory
[DEBUG] Shutting down 'semaphore-local' factory
[DEBUG] Shutting down 'noop' factory
```

**Comment by Kimrli** [comment] 2024-07-04 12:39
Works with libcolorscreen-0.dll build from commit f7de1f756294cd2fae653b2709a03d92aaed48a6.

**Comment by janhubicka** [comment] 2024-07-04 12:41
It is missing DLL_PUBLIC which seems to be needed now to instantiate the
new template class for dufay and paget analysis.
Does revision d7f70086ec1e613c2a81e30e5e85cf34a03ae5c0 work?

**Comment by Kimrli** [comment] 2024-07-05 09:50
It does. But GUI won't launch:
```
Exception in Application constructor
Exception in thread "main" java.lang.RuntimeException: Unable to construct Application instance: class cz.cuni.mff.java.digitalColoring.GUI.ColorScreenGUI
	at javafx.graphics@21/com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:883)
	at javafx.graphics@21/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:196)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.UnsatisfiedLinkError: L:\Documents\Color-Screen\Color-Screen-GUI\target\render.dll: Uveden� procedura nebyla nalezena
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:331)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:197)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:139)
	at java.base/jdk.internal.loader.NativeLibraries.findFromPaths(NativeLibraries.java:259)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:251)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2451)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:916)
	at java.base/java.lang.System.loadLibrary(System.java:2063)
	at cz.cuni.mff.java.digitalColoring@1.0-SNAPSHOT/cz.cuni.mff.java.digitalColoring.GUI.ColorScreenGUI.<clinit>(ColorScreenGUI.java:31)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1160)
	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.ensureClassInitialized(MethodHandleAccessorFactory.java:300)
	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.newConstructorAccessor(MethodHandleAccessorFactory.java:103)
	at java.base/jdk.internal.reflect.ReflectionFactory.newConstructorAccessor(ReflectionFactory.java:200)
	at java.base/java.lang.reflect.Constructor.acquireConstructorAccessor(Constructor.java:549)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at javafx.graphics@21/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$8(LauncherImpl.java:795)
	at javafx.graphics@21/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:483)
	at javafx.graphics@21/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:456)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at javafx.graphics@21/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:455)
	at javafx.graphics@21/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at javafx.graphics@21/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics@21/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:185)
	... 1 more
[ERROR] Command execution failed.
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
```

**Comment by janhubicka** [comment] 2024-07-05 12:02
Caused by: java.lang.UnsatisfiedLinkError:
L:\Documents\Color-Screen\Color-Screen-GUI\target\render.dll: Uveden�
procedura nebyla nalezena

This looks like missling DLL_EXPORT or perhaps mismatched header
files.  It is hard to say since it does not say what procedure

is missing.  Is it somewhere else in the log? Does MacOS version work?

Honza

**Comment by janhubicka** [comment] 2024-07-13 18:29
As discussed over email, I bleieve this is mismatch in code paths for GCC compilers.  We now biuld regularly Windows binaries as part of github testing and it builds and runs fine for me.  Lets open new issue if there is still a problem.

**Closed as completed by janhubicka** 2024-07-13 18:29 UTC
